# This workflow will build a Java project with Mav
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven  

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Wildfly Core CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-all:
    name: Compile (no tests) with JDK 8
    runs-on: ubuntu-latest
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            m2-
    - uses: actions/checkout@v2
    - name: Set up JDK8
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: 8
        impl: hotspot
    - name: Build
      run: mvn -U -B -fae -DskipTests clean install
    - name: Tar Maven Repo
      shell: bash
      run: tar -czf maven-repo.tgz -C ~ .m2/repository
    - name: Persist Maven Repo
      uses: actions/upload-artifact@v1
      with:
        name: maven-repo
        path: maven-repo.tgz
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-build
        path: '**/surefire-reports/*'
  test-matrix:
    name: JDK ${{ matrix.jdk }} - ${{ matrix.module }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
        # TODO automate this from var above
        module: ['', 'ts.domain', 'ts.rbac', 'ts.layers', 'ts.bootable', 'ipv6', 'security.manager', 'ts.patching', 'ts.manualmode']
        jdk: [8, 11]
    steps:
    - name: Update hosts - linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        cat /etc/hosts
        sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
        sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
    - name: Update hosts - windows
      if: contains(matrix.os, 'windows')
      run: |
        type %SystemRoot%\System32\drivers\etc\hosts
        echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > %SystemRoot%\System32\drivers\etc\hosts
        echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
      shell: cmd
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Host information
      run: |
       hostname || true
    - uses: actions/checkout@v2
    - name: Download Maven Repo
      uses: actions/download-artifact@v1
      with:
        name: maven-repo
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf maven-repo.tgz -C ~
    - name: Set up JDK ${{ matrix.jdk }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: 8
        impl: hotspot
    - name: Run Tests
      run: mvn -U -B -fae test '-DallTests' '-Dcheckstyle.skip=true' '-Denforcer.skip=true' --define=${{ matrix.module }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-${{ matrix.jdk }}-${{ matrix.module }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'
